id = "warehouse"
package = "warehouse"

[resources]
cpus = 1.0
mem_limit = 512

[process]
uid = 0
gid = 0
env = [
    "PORT=10022"
]
args = [
    "/usr/local/bin/run"
]

[services]
    [services.ssh]
    interface = "eth0"
    port = 10022
    port_type = "tcp"

    [[services.ssh.checks]]
    type = "tcp"
    interval = 10
